export const UPDATE_BOOKS = "UPDATE_BOOKS";
export const UPDATE_DISPLAY_BOOKS = "UPDATE_DISPLAY_BOOKS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const UPDATE_CURRENT_FILTER = "UPDATE_CURRENT_FILTER"; 

export const ADD_TO_CART = 'ADD_TO_CART'; 
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'; 
export const CLEAR_CART = 'CLEAR_CART'; 
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART'; 
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'; 

// FOR MOBILE DEVICES 
export const TOGGLE_CART = 'TOGGLE_CART'; 